### ISSUE TITLE
Very interesting approach, I like it

### ISSUE THREAD

**Issue by whyrusleeping** [feross/funding#3]
<3

**Comment by feross** [comment]
Thanks for the support, @whyrusleeping. Means a lot coming from you!

**Comment by substack** [comment]
I also like this. Working for free so that companies can make more money is terrible.

**Comment by traverseda** [comment]
@substack 

Then license under the AGPL and sell commercial licenses? Ads is just about the worst approach you could take to solve the "companies aren't paying for the software they use" problem. It's almost never individual developers who aren't paying their share, because unless they're a freelancer they're not making money off of your work. They're being paid by some company that's making money off of your work.

**Comment by kemitchell** [comment]
@traverseda how are developers taking pay from companies that don't support open source not making money off unsupported open source? Is the company supposed to know better than its developers what open work they're relying on, who is behind it, and whether they're fairly supported?

**Comment by traverseda** [comment]
I don't understand your question? Developers are generating revenue through their job, their job is generating revenue through open source. Yes, developers indirectly make money off of open source, and if you're a freelancer you're directly making money off-of open source. Does that answer your question?

**Comment by feross** [comment]
I appreciate the thoughtful discussion and feedback. I ended the experiment last week. I shared some thoughts about how the experiment went from my perspective on my blog: https://feross.org/funding-experiment-recap/
