### ISSUE TITLE
Request to end experiment

### ISSUE THREAD

**Issue by joshavanier** [feross/funding#7]
I think it's safe to say that the experiment is over what with all the mostly-negative feedback you've garnered in the past few days, wouldn't you agree? While I admire your efforts in finding new ways to fund open-source projects, plastering ads on people's terminals isn't the way to go.

I do not mean for this to come off as rude, but if you do see it that way, then you'd know how I felt when I bumped into your ads _twice_ this evening. The unwelcome sight I beheld was rude and intrusive, but thankfully short-lived. I can only imagine what visual horror my eyes would have been subjected to if more packages out there had followed suit. Terminals would turn into billboards.

Please consider concluding this experiment as soon as possible.

**Comment by kemitchell** [comment]
@joshavanier how could you expect this to come off as anything _but_ rude?

What are you proposing that @feross do instead? Nothing?

**Comment by joshavanier** [comment]
Not nothing, but definitely something else. I'll get back to you when I think of alternatives, @kemitchell

**Comment by Hamuko** [comment]
One thing you can do is contact abuse@npmjs.com. npm's Acceptable Content policy states that adware is unacceptable content and this package might fall into that category.

**Comment by azah** [comment]
> What are you proposing that @feross do instead? Nothing?

@kemitchell yes. F/OSS isn't about getting paid. If one feels like they need to get paid to write software, they can find a job and go develop proprietary software for a firm. (or, open source software if the firm is okay with open sourcing). That is preferable to polluting things like post-install logs with ads.

The author simply is not thinking about what will happen if -everyone- starts doing this.

**Comment by kemitchell** [comment]
@azah:

If you care about what early figures from the movements said, read Richard M. Stallman and Eric S. Raymond on F/OSS and money. Both wrote extensively on business models, and advised or ran some themselves. If you care more about companies, look into Netscape's founding of Mozilla or read Robert Young's book about Red Hat.

The author is thinking plenty about what this approach looks like at scale. There were several conversations here on this repo before it gained HN's attention, and at least several private conversations in various places before that. If you're genuinely interested, I suggest you catch up with him.

**Comment by azah** [comment]
> @azah:
> 
> If you care about what early figures from the movements said, read Richard M. Stallman and Eric S. Raymond on F/OSS and money. Both wrote extensively on business models, and advised or ran some themselves. If you care more about companies, look into Netscape's founding of Mozilla or read Robert Young's book about Red Hat.

I don't disagree? Founding a company or creating a business model is perfectly fine. Subjecting users to ads is unethical and not in the spirit of open source. Again, if money is such a strong desire, then a) figure out a business or b) get paid to write software for a company, either proprietary or open source.

> The author is thinking plenty about what this approach looks like at scale

I find this to be dubious at best. Right now, only there are only 2 known instances of advertising via post-install logs. Having every mildly-used open source library use ads is untenable.

By "thinking plenty" did you perhaps mean, "How much money can I make"? I find it very hard to believe one would launch ads with even a cursory thought about what that could do to the ecosystem.

**Comment by feross** [comment]
> Again, if money is such a strong desire, then a) figure out a business or b) get paid to write software for a company, either proprietary or open source.

Why do you think you are entitled to decide the methods I use to make money from my work?

> There should never be an -expectation- to get paid for F/OSS. It's a possibility no doubt, but not something one absolutely deserve

Maintainers need to pay their rent. What you seem to be saying is that maintainers should struggle in silence and hope for the best.

**Comment by azah** [comment]
> Why do you think you are entitled to decide the methods I use to make money from my work?

Why are you entitled to spam ads in postinstall logs? People read those, you know, just in case libraries have important/breaking updates. 

> Maintainers need to pay their rent. What you seem to be saying is that maintainers should struggle in silence and hope for the best.

Then find a job that pays your rent. I work on open source libraries like [generating Korean text from numbers](), [and free learning tools](https://apps.andrei.kr/), etc. Would it be nice if I got paid for that, considering that developing the algorithm and finely testing it with feedback from native speakers took well over 3 weeks of effort? Yeah.

The question however is do I **deserve** to be paid for that, to the point that I should spam people who install my rust crates with ads? No.

> What you seem to be saying is that maintainers should struggle in silence and hope for the best.

No, I'm saying that maintainers shouldn't **expect** to be paid, which you seem to be doing. Find a job and then you won't be "struggling in silence".

This funding library / spamming ads in *postinstall logs* are built on two things: entitlement and arrogance.

**Comment by modeco80** [comment]
> Maintainers need to pay their rent. What you seem to be saying is that maintainers should struggle in silence and hope for the best.

So, your solution here is to have hundreds of NPM packages now have popups upon installation? A bad solution, I must say.

**Comment by feross** [comment]
> Why are you entitled to spam ads in postinstall logs?

You chose to download and execute code that I published on the internet. If you don't like what the code does, then you should stop downloading it and executing it. It doesn't bother me if you choose to stop running my freely published code.

> What is the point of making something free (libre) software / open source if you don’t like it when people use it... as open source? 

Who said I don't want people to use software that I publish? Feel free to use it!

However, if you don't like the most version that was published, here are your options:

(1) stop using it
(2) fork it
(3) use an older version, which still works just as great as it always has

Just because software is published with a permissive license at one point in time, doesn't mean that you are guaranteed an infinite number of new versions (with new features, bug fixes, etc.) under the same terms, indefinitely into the future.

**Comment by Toxoid49b** [comment]
As I see it, you can't just create free software and then try and pull a fast one on people after they've already integrated it into their workflow with the assumption that it's free.

**Comment by kemitchell** [comment]
Developers making substantial contributions to the business efforts of others deserve fair recognition, monetary and otherwise, for their thought, skill, and labor, just like other contributors. Open source doesn't change basic fairness.

Some may choose to waive the expectation of receiving anything back, for any number of reasons. That is a valid choice, to be respected. But it doesn't follow from "open source". It's true that open source licenses provide free-of-charge licenses for specifics software artifacts. Nothing less, and nothing more. Nothing about services. Nothing about quality. Nothing about functionality. Nothing about future work.

Feross is making very clear that he _doesn't_ waive his expectation of fair support. Elsewhere, he's made clear that he thinks that fairness has not been respected. He's still licensing his work for free.

**Comment by kemitchell** [comment]
@Toxoid49b on what basis did people assume that Feross' future work would be free, and how has he deviated from that?

**Comment by petermikitsh** [comment]
It should be noted this project could violate NPM's Open Source terms:

> 3. Content containing malicious computer code, such as computer viruses, computer worms, rootkits, back doors, **adware**, or spyware. This includes content submitted for research purposes unless agreed to in advance by npm. Tools designed and documented explicitly to assist in security research are acceptable, but proof-of-concept exploits are not.

https://www.npmjs.com/policies/open-source-terms

If the project was silent by default, it could potentially not be classified as adware. This project has no functionality beyond serving ads, to my understanding.

**Comment by Toxoid49b** [comment]
@kemitchell  The software did not contain advertisements beforehand and the possibility of such a thing occurring was never clearly stated up until this point. Keep in mind by "free" I mean "not monetized". It is my opinion that advertisements constitute a form of payment from the end user, even if it is not strictly a monetary form of payment.

**Comment by kemitchell** [comment]
@Toxoid49b on what basis did people assume that Feross' future work would not be monetized?

**Comment by modeco80** [comment]
He had never tried a stunt like this until now, silly man.

**Comment by Toxoid49b** [comment]
Because it was never stated that it would be and it wasn't up until this point. This is fairly basic common sense. The project is also licensed under MIT, which explicitly states the software is _free of charge_. As I stated earlier, advertisements constitute a form of payment and as such contradict the license.

**Comment by kemitchell** [comment]
@Toxoid49b have you been charged?

**Comment by Toxoid49b** [comment]
Yes, advertisements appear in the terminal. It is a form of payment.

**Comment by kemitchell** [comment]
@Toxoid49b how much did you pay Feross?

**Comment by Toxoid49b** [comment]
@kemitchell  I paid him with the income he generated from the advertisement and the interruption it introduced into my workflow. Advertisements are generally considered invasive, something not particularly welcome in a professional workflow.

**Comment by kemitchell** [comment]
Advertisements _are_ generally considered invasive. But they are not generally considered payment.

**Comment by modeco80** [comment]
Please give an example of an advertisement that does not end up creating monetary value.

**Comment by Toxoid49b** [comment]
I would disagree with this position. When you download a free mobile game, for example, you generally expect that you're going to "pay" with advertisements. Many times, you can obtain free in-game items by willfully watching advertisements as a form of payment. This is, of course, an example meant to illustrate the concept and not meant to suggest that Feross's software can be classified as a game.

**Comment by Project-Magenta** [comment]
We get no reward for watching the advertisements. Free software is meant to be free.

**Comment by Project-Magenta** [comment]
@feross is still generating income off of us.
Even if we don't use the product, it makes him money, and for us, is only an annoyance.

**Comment by mixmix** [comment]
**META** - I recommend we start another thread something like "What is Open Source to you ?" because there are many different ideas here, which is what I thnk is generating a lot of tension

**Comment by gizmo385** [comment]
@mixmix Is there not a worry about over-partitioning the conversations into a bunch of different issue threads that eventually just become disconnected from the overall discussion?

**Comment by Project-Magenta** [comment]
@gizmo385 I think he wants to silence us by putting "rules" at the end of the issue saying something like: :x: No complaining about this module

**Comment by modeco80** [comment]
> @gizmo385 I think he wants to silence us by putting "rules" at the end of the issue, saying something like:
>  No complaining about this module

Even if he does do that, there is exactly ZERO point. The maintainer of this module has already no-op'd it (by adding a check and clearing out the messages file) and is most likely getting ready to delete it at any point. I hate to say it, but I feel as if this guy thought he was entitled to money, later realized he fucked over his entire reputation, and is now pulling out to save what little reputation he can (basically none)

**Comment by ChoHag** [comment]
Free Software isn't not about getting paid either. If anyone wants to actually be a disciple of RMS they would do well to read his earlier rantings which were well divided between the liberation of software and the means to be paid for producing it.

If the author of whatever this is wishes to include advertising in his or her product, then more power to them. I applaud the effort to get paid and the experimental nature on display here. I for one will not be touching it with a barge pole because adverts can sod off even harder than javascript but I value this thing called "freedom" (you may be aware of it) and feross is quite free as far as I'm concerned to do with this product anything at all as I, and all of you, are free to not use it or copy and change it to suit our own ends.

If you can't do that, learn programming. In any event, stop whining. It's not yours. Put up or shut up.

**Comment by evandentremont** [comment]
@gizmo385 I think that's the point.

**Comment by ChoHag** [comment]
That's truly fascinating but exactly how much control do you have over this repository? Oh that's right...

I am not a catalyst to this plague. I do not allow disgraces such as this on my computers or any which I maintain. The catalyst which has enabled this plague has been brewing for years already quite without my support while the IT industry trundled merrily along, oblivious.

I'm the first to complain when idiot developers use "just fork it or write your own" as an excuse to cover up their incompetence but this is not the case here. This is a person's own code and that person is as free to screw it up as you are all free to not use it.

Grow up.

**Comment by ChoHag** [comment]
Let's be quite clear:

Advertising is bollocks.

This repository belongs to feross (as per an agreement with GitHub née Microsoft).

The code contained within the repository has been released up to now under a (cancerous but) do-what-you-want license.

Anybody can do what they want with this code.

What they want includes not using it.

What they want includes removing parts of it that they don't like and maintaining it on their own, including uploading it in replacement to npm or whatever package-manager-du-jour is under scrutiny here.

What they want includes not learning jack and expecting somebody else to perform all the development and maintenance work without the form of remuneration they feel is due.

Everyone gets to choose. That's the wonderful thing about the principle of "freedom" that underlies the philosophy of "free software". You get to choose to pay someone what they demand for their work, or do the work yourself, or sod off.

People died by the millions so that you could have that option today.

**Comment by tobico** [comment]
As someone who's generally not a fan of ads and uses an Ad-blocker whenever I can, I'm surprised to say that I actually quite like the idea of ads supporting open source.

I think it could work well in getting around the problem of the software decision makers (e.g. developers) not being the financial decision makers (e.g. senior management) in most organizations. Ads give developers the ability to support OSS with something valuable (their attention), which they also have the agency to be able to provide even within the largest and most bureaucratic organization.

Please don't be put off by all the hate, people are always going to complain when an attempt is made to charge for something they're accustomed to getting for free, but the loudest voices don't speak for everyone, and I personally think it's well worth putting up with a little inconvenience if it helps the OSS community stay healthy and well-resourced.

**Comment by niklas-heer** [comment]
I think there are a lot of angles and views regarding the topic of what open source actually is and how should it be funded, but what I found shocking is the emotions and quite harsh comments with accusations based on personal view points.

In my opinion thinking about getting open source contributors compensated for their outstanding work is a good thing. Also trying out such ways should be possible and it should also be possible for people to share their views how they think of such experiments.
It is an easy thing to bash this project, but in my eyes it has brought an interesting angle to the discussion about sustainable open source.

In my experience a calm, objective discussion based on respect and the believe of the others good intentions (although they might be different from my preferences/opinions) is more productive. :slightly_smiling_face:

**Comment by derrickmehaffy** [comment]
For those unaware NPM is now changing their policies to ensure there will be no more experiments like this: https://www.zdnet.com/article/npm-bans-terminal-ads/

Also It would seem the experiment is now over.

**Comment by feross** [comment]
I appreciate the thoughtful discussion and feedback. I ended the experiment last week. I shared some thoughts about how the experiment went from my perspective on my blog: https://feross.org/funding-experiment-recap/
